name: Oukami
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.1
  flappy_search_bar: ^1.7.2
  google_fonts: ^1.1.0
  cached_network_image: 
  flutter_email_sender: ^3.0.1
  flutter_web_browser: ^0.11.0
  share: ^0.6.4+3
  flutter_sticky_header: ^0.4.2
  zoom_widget: ^0.1.3
  matrix_gesture_detector: ^0.1.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: 
  font_awesome_flutter: ^8.8.1
  cupertino_icons: ^0.1.3
  flutter_modular: any
  bottom_navy_bar: ^5.4.0
  simple_search_bar: ^0.1.7
  http: ^0.12.2
  percent_indicator: ^2.1.5
  dio: ^3.0.9
  intl: ^0.16.1
  fluttertoast: ^4.0.1
  shimmer: ^1.1.1
  material_design_icons_flutter:
  flutter_icons: ^1.0.0+1
  shared_preferences: ^0.5.4+3  
  scroll_app_bar:
  gradient_app_bar: ^0.1.0
  expand_widget: ^0.2.0+2
  carousel_slider: ^2.2.1
  flutter_curved_tab_bar:
  flutter_point_tab_bar: 
  equatable: ^1.2.5
  get_it: ^5.0.1
  connectivity: ^0.4.9+5
  extended_image: 
  flutter_screenutil: ^2.2.0
  easy_localization: ^2.3.3
  cool_alert: ^1.0.1
  line_icons: ^0.2.0
  system_setting:
  cupertino_range_slider: ^1.0.1
  cupertino_setting_control:
  flutter_cache_manager: ^2.0.0
  shelf: ">=0.7.0 <0.8.0"
  splashscreen:
  flutter_automation: ^1.4.0

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.8.0
  
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/iconFull1000.png"  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    - lib/assets/backgrounds/
    - lib/assets/test/
    - lib/assets/search/images/
    - lib/assets/bar/
    - lib/assets/home/
    - lib/assets/home/images/  
    - lib/assets/search/
    - lib/assets/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
    - family: Poppins-Medium
      fonts:
        - asset: lib/assets/fonts/Poppins-Medium.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: lib/assets/fonts/Poppins-SemiBold.ttf
    # - family: Slim Summer
    #   fonts:
    #     - asset: lib/assets/fonts/Slim Summer.ttf
    - family: Stanberry
      fonts:
        - asset: lib/assets/fonts/Stanberry.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

